# Generated by Django 5.1.6 on 2025-02-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correct',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
